version: "3"

services:
  api:
    build: ./code/
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-http.rule=Host(`velomag.chickenkiller.com`)
      - traefik.http.routers.app-http.tls=true
      - traefik.http.routers.app-http.tls.certresolver=letsencrypt

  traefik:
    image: traefik:v2.3
    ports:
      - 55555:80
      - 55556:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - traefik-public-certificates:/certificates

volumes:
  traefik-public-certificates:
